CREATE TABLE specialite (
	id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	nom VARCHAR(255) NOT NULL
);

CREATE TABLE roles (
	id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	role VARCHAR(3) UNIQUE NOT NULL
);

CREATE TABLE utilisateur (
	id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1001 MAXVALUE 2000),
	nom VARCHAR(100) NOT NULL,
	prenom VARCHAR(100) NOT NULL,
	email VARCHAR(100) UNIQUE NOT NULL,
	password VARCHAR(100) NOT NULL,
	role INT NOT NULL,
	age INT,
	CONSTRAINT fk_role FOREIGN KEY (role) REFERENCES roles(id) ON DELETE CASCADE ON UPDATE CASCADE 
);

CREATE TABLE patient (
	id INT PRIMARY KEY,
	CONSTRAINT fk_utilisateur FOREIGN KEY (id) REFERENCES utilisateur(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE medecin (
	matricule VARCHAR(5) PRIMARY KEY,
	id INT NOT NULL,
	specialite INT NOT NULL,
	CONSTRAINT fk_utilisateur FOREIGN KEY (id) REFERENCES utilisateur(id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT fk_specialite FOREIGN KEY (specialite) REFERENCES specialite(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE secretaire (
	matricule VARCHAR(5) PRIMARY KEY,
	id INT NOT NULL,
	CONSTRAINT fk_utilisateur FOREIGN KEY (id) REFERENCES utilisateur(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE creneau (
	id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	heureDebut TIME NOT NULL,
	heureFin TIME NOT NULL,
	medecin VARCHAR(3) NOT NULL,
	CONSTRAINT fk_medecin FOREIGN KEY (medecin) REFERENCES medecin(matricule) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE rdv (
	id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	dateProgrammation Date NOT NULL,
	datePrevu Date NOT NULL,
	heureDebut TIME NOT NULL,
	heureFin TIME NOT NULL,
	patient INT NOT NULL,
	medecin VARCHAR(3) NOT NULL,
	CONSTRAINT fk_patient FOREIGN KEY (patient) REFERENCES patient(id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT fk_medecin FOREIGN KEY (medecin) REFERENCES medecin(matricule) ON DELETE CASCADE ON UPDATE CASCADE
);